#!/bin/bash

echo "🧪 Test de connexion avec les identifiants"
echo "=========================================="
echo ""
echo "📋 Identifiants à tester après migration Supabase :"
echo ""
echo "👨‍🏫 PROFESSEUR :"
echo "   Identifiant: ruxdl"
echo "   Mot de passe: MdpCPRDV6737"
echo "   ➜ Redirection attendue: /prof"
echo ""
echo "👨‍🎓 ÉTUDIANT 1 :"
echo "   Identifiant: Hamza6E" 
echo "   Mot de passe: MdpHamza6ET"
echo "   ➜ Redirection attendue: /student"
echo ""
echo "👩‍🎓 ÉTUDIANT 2 :"
echo "   Identifiant: ELISE4EEMMA1E"
echo "   Mot de passe: MdpEE4E1E"
echo "   ➜ Redirection attendue: /student"
echo ""
echo "⚠️  IMPORTANT :"
echo "   1. Exécutez d'abord le script database/SIMPLE-UPDATE-AUTH.sql dans Supabase"
echo "   2. Testez ensuite la connexion sur le site"
echo "   3. Le formulaire demande maintenant 'Identifiant (pas email !)'"
echo ""
echo "🌐 URLs de test :"
echo "   Local: http://localhost:3000/auth"
echo "   Production: https://ruxdl.github.io/RDV-CP/auth"
